# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of npm package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "rubygems" # See documentation for possible values
    directory: "/" # Location of RubyGems package manifests
    schedule:
      interval: "daily"
  # Add more entries for other ecosystems as needed
