name: CI
on: push
jobs:
  trigger-lighthouse-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Lighthouse Metrics
        uses: lighthouse-metrics/github-actions@master
        with:
          url: 'https://www.addcolour.design'
          token: ${{ secrets.LIGHTHOUSE_METRICS_TOKEN }}
